%--------------------------------------------------------------------------
% FLWTFEM MATLAB SOLVER for FINITE ELEMENT ANALYSIS OF MULTILAYER PLATES
% BASED ON THE FULL LAYERWISE THEORY OF REDDY
% Developed by: Miroslav Marjanovic, PhD Civil Eng.
%               Emilija Damnjanovic, MSc Civil Eng.
%               Belgrade, 2019.
%--------------------------------------------------------------------------
function [shape,NatDev,SecDev] = Shape(elemtype,xi,eta)
%--------------------------------------------------------------------------
% This function evaluates shape functions and their derivatives at
% prescribed quadrature points depending on a chosen element type.
%
%  INPUT DATA:
%      elemtype - the type of 2D finite element
%      xi,eta   - coordinates of the 2D Gauss quadrature points
%
%  OUTPUT DATA:
%      Shape  - values of shape functions at the quadrature points
%               size(shape) = 1 x ELEMNODES
%      NatDev - first derivatives of shape functions at the quadrature
%               points with respect to "xi" and "eta"
%               size(NatDev) = ELEMNODES x 2
%      SecDev - second derivatives of shape functions at the quadrature
%               points with respect to "xi xi", "eta eta" and "xi eta"
%               size(SecDev) = ELEMNODES x 3
%--------------------------------------------------------------------------
switch elemtype
    
    case 'Q4'
        % 4-Node Quadrilateral Element
        shape  = 0.25 * [(1-xi)*(1-eta) (1+xi)*(1-eta)...
                         (1+xi)*(1+eta) (1-xi)*(1+eta)];
        NatDev = 0.25 * [eta-1 xi-1; 1-eta -1-xi;...
                         1+eta 1+xi; -1-eta 1-xi];
        SecDev = 0.25 * [0 0 1;   0 0 -1;   0 0 1;   0 0 -1];
        
        
    case 'Q8'
        % 8-Node Quadrilateral Element
        shape = -0.25 * [(1-xi)*(1-eta)*(1+xi+eta)...
            (1+xi)*(1-eta)*(1-xi+eta)...
            (1+xi)*(1+eta)*(1-xi-eta)...
            (1-xi)*(1+eta)*(1+xi-eta)...
            (-2+2*xi^2)*(1-eta)...
            (-2-2*xi)*(1-eta^2)...
            (-2+2*xi^2)*(1+eta)...
            (-2+2*xi)*(1-eta^2)];
        
        NatDev = [-0.25*(xi-1)*(eta-1) - 0.25*(eta-1)*(eta+xi+1) ...
            -0.25*(xi-1)*(eta-1) - 0.25*(xi-1)*(eta+xi+1);...
            0.25*(eta-1)*(eta-xi+1) - 0.25*(xi+1)*(eta-1) ...
            0.25*(xi+1)*(eta-xi+1) + 0.25*(xi+1)*(eta-1);
            0.25*(xi+1)*(eta+1) + 0.25*(eta+1)*(eta+xi-1) ...
            0.25*(xi+1)*(eta+1) + 0.25*(xi+1)*(eta+xi-1);
            0.25*(xi-1)*(eta+1) + 0.25*(eta+1)*(xi-eta+1) ...
            0.25*(xi-1)*(xi-eta+1) - 0.25*(xi-1)*(eta+1);
            xi*(eta-1) 0.5*(xi^2-1);...
            0.5*(1-eta^2) -eta*(xi+1);...
            -xi*(eta+1) 0.5*(1-xi^2);...
            0.5*(eta^2-1) eta*(xi-1)];
        
        SecDev = [-0.25*(eta-1)-0.25*(eta-1) -0.25*(xi-1)-0.25*(xi-1)...
            -0.25*(xi-1)-0.25*(eta+xi+1)-0.25*(eta-1);...
            -0.25*(eta-1)-0.25*(eta-1) 0.25*(xi+1)+0.25*(xi+1)...
            0.25*(eta-xi+1)+0.25*(eta-1)-0.25*(xi+1);...
            0.25*(eta+1)+0.25*(eta+1) 0.25*(xi+1)+0.25*(xi+1)...
            0.25*(xi+1)+0.25*(eta+xi-1)+0.25*(eta+1);...
            0.25*(eta+1)+0.25*(eta+1) -0.25*(xi-1)-0.25*(xi-1)...
            0.25*(xi-1)+0.25*(xi-eta+1)-0.25*(eta+1);...
            eta-1  0     xi;...
            0      -xi-1 -eta;...
            -eta-1 0     -xi;...
            0      xi-1  eta];
        
        
    case 'T3'
        % 3-Node Triangular Element
        shape = [xi  eta  1-xi-eta];
        NatDev = [1 0; 0 1; -1 -1];
        SecDev = zeros(3);
        
        
    case 'T6'
        % 6-Node Triangular Element
        shape  = [xi*(2*xi-1)  eta*(2*eta-1)  (1-xi-eta)*(1-2*xi-2*eta)...
                  4*xi*eta  4*eta*(1-xi-eta)  4*xi*(1-xi-eta)];
        NatDev = [4*xi-1 0;  0 4*eta-1;  4*xi+4*eta-3 4*xi+4*eta-3;...
                  4*eta 4*xi;  -4*eta 4-8*eta-4*xi;  4-4*eta-8*xi -4*xi];
        SecDev = [4 0 0;  0 4 0;  4 4 4;  0 0 4;  0 -8 -4;  -8 0 -4];
        
    otherwise; disp('Error: Unsupported element type');
end